#!/usr/bin/env bash
# Writes Config/Secrets.xcconfig from .env (gitignored). Run from repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${KBAPP_ENV_FILE:-$ROOT/.env}"
OUT="$ROOT/Config/Secrets.xcconfig"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing $ENV_FILE — copy env.example to .env and set KBAPP_API_BASE_URL / KBAPP_AUTH_TOKEN." >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a
source "$ENV_FILE"
set +a

base="${KBAPP_API_BASE_URL:-}"
token="${KBAPP_AUTH_TOKEN:-}"

if [[ -z "$base" || -z "$token" ]]; then
  echo "Set KBAPP_API_BASE_URL and KBAPP_AUTH_TOKEN in $ENV_FILE" >&2
  exit 1
fi

# xcconfig treats "//" as end-of-line comment — escape slashes for https:// hosts.
xcconfig_url() {
  local url="$1"
  if [[ "$url" =~ ^https://(.+)$ ]]; then
    printf 'https:$(SLASH)$(SLASH)%s' "${BASH_REMATCH[1]}"
  elif [[ "$url" =~ ^http://(.+)$ ]]; then
    printf 'http:$(SLASH)$(SLASH)%s' "${BASH_REMATCH[1]}"
  else
    printf '%s' "$url"
  fi
}

base_xc="$(xcconfig_url "$base")"

cat > "$OUT" <<EOF
// Generated by scripts/sync-secrets-xcconfig.sh — do not commit
SLASH = /
KBAPP_API_BASE_URL = $base_xc
KBAPP_AUTH_TOKEN = $token
INFOPLIST_KEY_KBAppAPIBaseURL = \$(KBAPP_API_BASE_URL)
INFOPLIST_KEY_KBAppAuthToken = \$(KBAPP_AUTH_TOKEN)
EOF

echo "Wrote $OUT"
